# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets
from GuiApp.DateEdit import DateEdit


class UiMainWindow(object):
    """
    Главное окно приложения
    """
    def __init__(self, main_window):
        # Главное окно и центральный виджет
        self.main_window = main_window
        self.central_widget = QtWidgets.QWidget(self.main_window)
        self.central_widget.setObjectName("centralwidget")

        # Создание виджета вкладок окон и создание в нем две вкладки: "заказы", "ингредиенты"
        self.tab = QtWidgets.QTabWidget(self.central_widget)
        self.tab_1 = QtWidgets.QWidget()
        self.tab_2 = QtWidgets.QWidget()

        # TAB1. Создание таблицы и кнопок управления таблицей
        self.tbl = QtWidgets.QTableWidget(self.tab_1)
        # self.tbl.setSortingEnabled(False)
        self.btn_load = QtWidgets.QPushButton(self.tab_1)
        self.btn_del = QtWidgets.QPushButton(self.tab_1)
        self.btn_add = QtWidgets.QPushButton(self.tab_1)
        self.btn_save = QtWidgets.QPushButton(self.tab_1)
        self.lbl_info = QtWidgets.QLabel(self.tab_1)  # Метка, отображающая результат после нажатия кнопок

        # TAB2. Создания списка ингредиентов, кнопок и меток для управления списком
        self.list_ingr = QtWidgets.QListWidget(self.tab_2)
        self.lbl_pick_ingredient = QtWidgets.QLabel(self.tab_2)
        self.lbl_begin_date = QtWidgets.QLabel(self.tab_2)
        self.lbl_end_date = QtWidgets.QLabel(self.tab_2)
        # Выбор даты начала и конца для поиска суммы игредиентов по заказам за этот промежуток
        self.date_begin_ingr = DateEdit(self.tab_2)
        self.date_end_ingr = DateEdit(self.tab_2)
        # Выбор ингредиента, по которому будет осуществляться поиск суммы игредиентов
        self.combo_ingr = QtWidgets.QComboBox(self.tab_2)
        self.btn_list_update = QtWidgets.QPushButton(self.tab_2)

        self.setup_ui()

    def setup_ui(self):
        """
        Изменение свойств виджетов
        """
        font = [QtGui.QFont(), QtGui.QFont(), QtGui.QFont()]
        font[0].setFamily("Bahnschrift Light")
        font[0].setPointSize(12)
        font[1].setFamily("Bahnschrift Light")
        font[1].setPointSize(14)
        font[2].setFamily("Arial")
        font[2].setPointSize(20)

        self.main_window.setObjectName("MainWindow")
        self.main_window.setWindowTitle("Система управления заказами")
        self.main_window.resize(1280, 720)
        self.main_window.setMinimumSize(QtCore.QSize(1280, 720))
        self.main_window.setFont(font[0])
        self.main_window.setCentralWidget(self.central_widget)

        self.tab.setGeometry(QtCore.QRect(30, 40, 1211, 641))
        self.tab.setObjectName("tab")
        self.tab.setCurrentIndex(0)

        self.tab_1.setObjectName("tab_1")
        self.tab.addTab(self.tab_1, "Заказы")

        self.tab_2.setObjectName("tab_2")
        self.tab.addTab(self.tab_2, "Ингредиенты")

        self.tbl.setGeometry(QtCore.QRect(70, 80, 1075, 371))
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(7)
        self.tbl.setRowCount(0)
        self.tbl.setHorizontalHeaderLabels(
            ["ID", "Фио", "Телефон", "Название торта", "Дата принятия", "Дата выдачи", "Цена торта"])
        for i in range(1, 8):  # выставление ширины заголовков в таблице
            self.tbl.setColumnWidth(i, 160)

        self.btn_load.setGeometry(QtCore.QRect(930, 500, 261, 50))
        self.btn_load.setObjectName("btn_load")
        self.btn_load.setText("Загрузить")
        self.btn_load.setFont(font[2])

        self.btn_save.setGeometry(QtCore.QRect(670, 500, 221, 50))
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setText("Сохранить")
        self.btn_save.setFont(font[2])

        self.btn_add.setGeometry(QtCore.QRect(440, 500, 201, 51))
        self.btn_add.setObjectName("btn_add")
        self.btn_add.setText("Добавить")
        self.btn_add.setFont(font[2])

        self.btn_del.setGeometry(QtCore.QRect(180, 500, 201, 51))
        self.btn_del.setObjectName("btn_del")
        self.btn_del.setText("Удалить")
        self.btn_del.setFont(font[2])

        self.lbl_info.setGeometry(QtCore.QRect(60, 470, 181, 16))
        self.lbl_info.resize(1000, 20)
        self.lbl_info.setObjectName("lbl_info")

        self.list_ingr.setGeometry(QtCore.QRect(760, 10, 441, 591))
        self.list_ingr.setObjectName("list_ingr")
        self.list_ingr.setFont(font[1])

        self.btn_list_update.setGeometry(QtCore.QRect(20, 560, 121, 31))
        self.btn_list_update.setObjectName("btn_list")
        self.btn_list_update.setText("Обновить")

        self.date_begin_ingr.setGeometry(QtCore.QRect(80, 20, 110, 22))
        self.date_begin_ingr.setCalendarPopup(True)
        self.date_begin_ingr.setObjectName("date_begin_ingr")

        self.date_end_ingr.setGeometry(QtCore.QRect(270, 20, 110, 22))
        self.date_end_ingr.setCalendarPopup(True)
        self.date_end_ingr.setObjectName("date_end_ingr")

        self.lbl_begin_date.setGeometry(QtCore.QRect(0, 10, 81, 41))
        self.lbl_begin_date.setFont(font[1])
        self.lbl_begin_date.setText("Начало: ")
        self.lbl_begin_date.setObjectName("lbl_info_2")

        self.lbl_end_date.setGeometry(QtCore.QRect(200, 10, 81, 41))
        self.lbl_end_date.setFont(font[1])
        self.lbl_end_date.setText("Конец: ")
        self.lbl_end_date.setObjectName("lbl_info_3")

        self.lbl_pick_ingredient.setGeometry(QtCore.QRect(0, 60, 111, 31))
        self.lbl_pick_ingredient.setFont(font[1])
        self.lbl_pick_ingredient.setText("Ингредиент: ")
        self.lbl_pick_ingredient.setObjectName("lbl_info_4")

        self.combo_ingr.setGeometry(QtCore.QRect(130, 70, 201, 21))
        self.combo_ingr.setObjectName("combo_ingr")
