# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import Qt
# os.system('Pyrcc5 file.qrc -o file_qrc.py')


class UiMainWindow(object):
    def __init__(self, main_window):
        self.main_window = main_window

        self.styles = QtWidgets.QWidget(self.main_window)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.styles)
        self.main_body = QtWidgets.QFrame(self.styles)
        self.main_header = QtWidgets.QFrame(self.styles)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.tittle_bar_container = QtWidgets.QFrame(self.main_header)
        self.lbl_title = QtWidgets.QLabel(self.main_header)
        self.btns_navigation = QtWidgets.QFrame(self.main_header)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tittle_bar_container)
        self.left_menu_toggle = QtWidgets.QFrame(self.tittle_bar_container)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toggle)
        self.btn_toggle = QtWidgets.QPushButton(self.left_menu_toggle)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.btns_navigation)
        self.btn_restore = QtWidgets.QPushButton(self.btns_navigation)
        self.btn_min = QtWidgets.QPushButton(self.btns_navigation)
        self.btn_close = QtWidgets.QPushButton(self.btns_navigation)

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.central_body = QtWidgets.QFrame(self.main_body)

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.btn_home_menu = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_orders_menu = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_products_menu = QtWidgets.QPushButton(self.left_side_menu)

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_body)
        self.middle_body = QtWidgets.QFrame(self.central_body)
        self.main_footer = QtWidgets.QFrame(self.central_body)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.main_footer)
        self.lbl_info_tbl = QtWidgets.QLabel(self.main_footer)
        self.size_grip = QtWidgets.QFrame(self.main_footer)

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.middle_body)
        self.stacked_widget = QtWidgets.QStackedWidget(self.middle_body)

        self.home_page = QtWidgets.QWidget()
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.home_page)
        self.lbl_home = QtWidgets.QLabel(self.home_page)
        self.body_frame = QtWidgets.QFrame(self.home_page)

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body_frame)
        self.lbl_del_home = QtWidgets.QLabel(self.body_frame)
        self.lbl_add_home = QtWidgets.QLabel(self.body_frame)
        self.lbl_edit_home = QtWidgets.QLabel(self.body_frame)
        self.lbl_ingr_home = QtWidgets.QLabel(self.body_frame)
        self.lbl_search_home = QtWidgets.QLabel(self.body_frame)

        self.orders_page = QtWidgets.QWidget()
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.orders_page)
        self.orders_cost = QtWidgets.QFrame(self.orders_page)
        self.tbl = QtWidgets.QTableWidget(self.orders_page)
        self.btns_table = QtWidgets.QFrame(self.orders_page)

        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.orders_cost)
        self.lbl_cost = QtWidgets.QLabel(self.orders_cost)

        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.btns_table)
        self.btn_add = QtWidgets.QPushButton(self.btns_table)
        self.btn_del = QtWidgets.QPushButton(self.btns_table)
        self.btn_save = QtWidgets.QPushButton(self.btns_table)
        self.btn_load = QtWidgets.QPushButton(self.btns_table)

        self.products_page = QtWidgets.QWidget()
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.products_page)
        self.body_products = QtWidgets.QFrame(self.products_page)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.body_products)
        self.left_body = QtWidgets.QFrame(self.body_products)

        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.left_body)
        self.lbl_ingredients = QtWidgets.QLabel(self.left_body)
        self.list_ingredients = QtWidgets.QListWidget(self.left_body)
        self.btn_products = QtWidgets.QPushButton(self.left_body)

        self.right_body = QtWidgets.QFrame(self.body_products)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.right_body)
        self.sort_ingredients = QtWidgets.QFrame(self.right_body)
        self.empty_frame = QtWidgets.QFrame(self.right_body)

        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sort_ingredients)
        self.lbl_date_begin = QtWidgets.QLabel(self.sort_ingredients)
        self.date_begin_ingr = QtWidgets.QDateEdit(self.sort_ingredients)
        self.lbl_date_end = QtWidgets.QLabel(self.sort_ingredients)
        self.date_end_ingr = QtWidgets.QDateEdit(self.sort_ingredients)
        self.lbl_combo_ingr = QtWidgets.QLabel(self.sort_ingredients)
        self.combo_ingr = QtWidgets.QComboBox(self.sort_ingredients)

    def setup_ui(self):
        self.main_window.setObjectName("MainWindow")
        self.main_window.resize(1300, 600)
        self.main_window.setStyleSheet(open('./GuiApp/ui.stylesheet').read())
        self.main_window.setCentralWidget(self.styles)

        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.horizontalLayout.addWidget(self.central_body)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.addWidget(self.tittle_bar_container, 0, Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.lbl_title)
        self.horizontalLayout_2.addWidget(self.btns_navigation)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.addWidget(self.btn_restore)
        self.horizontalLayout_3.addWidget(self.btn_min)
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_4.addWidget(self.btn_toggle)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_5.addWidget(self.left_menu_toggle, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_6.addWidget(self.stacked_widget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_7.addWidget(self.lbl_info_tbl, 0, Qt.AlignVCenter)
        self.horizontalLayout_7.addWidget(self.size_grip, 0, Qt.AlignRight | Qt.AlignBottom)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.addWidget(self.btn_save)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_8.addWidget(self.btn_add)
        self.horizontalLayout_8.addWidget(self.btn_del)
        self.horizontalLayout_8.addWidget(self.btn_load)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_9.addWidget(self.lbl_cost, 0, Qt.AlignHCenter | Qt.AlignVCenter)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_10.addWidget(self.left_body)
        self.horizontalLayout_10.addWidget(self.right_body)

        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.addWidget(self.main_header)
        self.verticalLayout.addWidget(self.main_body)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.addWidget(self.middle_body)
        self.verticalLayout_2.addWidget(self.main_footer)
        self.verticalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.addWidget(self.btn_home_menu)
        self.verticalLayout_3.addWidget(self.btn_orders_menu)
        self.verticalLayout_3.addWidget(self.btn_products_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_4.addWidget(self.lbl_del_home, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.lbl_add_home, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.lbl_edit_home, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.lbl_ingr_home, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.verticalLayout_4.addWidget(self.lbl_search_home, 0, Qt.AlignLeft | Qt.AlignVCenter)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_5.addWidget(self.tbl)
        self.verticalLayout_5.addWidget(self.orders_cost)
        self.verticalLayout_5.addWidget(self.btns_table, 0, Qt.AlignBottom)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_6.addWidget(self.body_products)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_7.addWidget(self.lbl_date_begin)
        self.verticalLayout_7.addWidget(self.date_begin_ingr)
        self.verticalLayout_7.addWidget(self.lbl_date_end)
        self.verticalLayout_7.addWidget(self.date_end_ingr)
        self.verticalLayout_7.addWidget(self.lbl_combo_ingr)
        self.verticalLayout_7.addWidget(self.combo_ingr)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_8.addWidget(self.lbl_ingredients)
        self.verticalLayout_8.addWidget(self.list_ingredients)
        self.verticalLayout_8.addWidget(self.btn_products)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_9.addWidget(self.sort_ingredients)
        self.verticalLayout_9.addWidget(self.empty_frame)
        self.verticalLayout_11.addWidget(self.lbl_home)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_11.addWidget(self.body_frame)

        self.stacked_widget.addWidget(self.orders_page)
        self.stacked_widget.addWidget(self.home_page)
        self.stacked_widget.addWidget(self.products_page)

        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")

        self.tittle_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tittle_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tittle_bar_container.setObjectName("tittle_bar_container")

        self.left_menu_toggle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toggle.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_menu_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toggle.setObjectName("left_menu_toggle")

        self.btn_toggle.setObjectName("btn_toggle")
        self.btn_toggle.setCursor(QtGui.QCursor(Qt.PointingHandCursor))

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/menu-dots-vertical-free-icon-font.png"),
                       QIcon.Normal, QIcon.Off)
        self.btn_toggle.setIcon(icon)
        self.btn_toggle.setIconSize(QtCore.QSize(24, 24))

        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)

        self.lbl_title.setSizePolicy(size_policy)
        self.lbl_title.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_title.setAlignment(Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_title.setText("Кондитерская 'Еще кусочек'")

        self.btns_navigation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.btns_navigation.setObjectName("btns_navigation")

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/resize-free-icon-font.png"), QIcon.Normal, QIcon.Off)
        self.btn_restore.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.btn_restore.setIcon(icon1)
        self.btn_restore.setIconSize(QtCore.QSize(24, 24))
        self.btn_restore.setFlat(True)
        self.btn_restore.setObjectName("btn_restore")

        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/minus-free-icon-font.png"), QIcon.Normal, QIcon.Off)
        self.btn_min.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.btn_min.setIcon(icon2)
        self.btn_min.setIconSize(QtCore.QSize(24, 24))
        self.btn_min.setFlat(True)
        self.btn_min.setObjectName("btn_min")

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/cross-free-icon-font.png"), QIcon.Normal, QIcon.Off)
        self.btn_close.setCursor(QtGui.QCursor(Qt.PointingHandCursor))
        self.btn_close.setIcon(icon3)
        self.btn_close.setIconSize(QtCore.QSize(24, 24))
        self.btn_close.setFlat(True)
        self.btn_close.setObjectName("btn_close")

        self.main_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")

        self.left_side_menu.setMinimumSize(QtCore.QSize(50, 200))
        self.left_side_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")

        self.btn_home_menu.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_home_menu.setObjectName("btn_home_menu")
        self.btn_home_menu.setText("Главная")
        self.btn_home_menu.setCursor(QtGui.QCursor(Qt.PointingHandCursor))

        self.btn_orders_menu.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_orders_menu.setObjectName("btn_orders_menu")
        self.btn_orders_menu.setText("Заказы")
        self.btn_home_menu.setCursor(QtGui.QCursor(Qt.PointingHandCursor))

        self.btn_products_menu.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_products_menu.setObjectName("btn_products_menu")
        self.btn_products_menu.setText("Продукты")
        self.btn_home_menu.setCursor(QtGui.QCursor(Qt.PointingHandCursor))

        self.central_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central_body.setObjectName("central_body")

        self.middle_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.middle_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_body.setObjectName("middle_body")

        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())

        self.stacked_widget.setSizePolicy(size_policy)
        self.stacked_widget.setStyleSheet("background-color:transparent;")
        self.stacked_widget.setObjectName("stacked_widget")

        self.home_page.setObjectName("home_page")

        self.lbl_home.setMaximumSize(QtCore.QSize(16777215, 70))
        self.lbl_home.setAlignment(Qt.AlignCenter)
        self.lbl_home.setObjectName("lbl_home")
        self.lbl_home.setText("Возможности данной программы")
        self.lbl_home.setStyleSheet("""background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, 
                                    stop:0.568182 rgba(255, 154, 170, 255), stop:1 rgba(246, 148, 164, 95));
                                    """)

        self.body_frame.setObjectName("body_frame")
        self.body_frame.setStyleSheet("""QLabel {
                                          background-color: rgb(255, 198, 208);
                                      }
                                      QLabel:hover{
                                          background-color:rgb(254, 170, 183);}""")

        self.lbl_del_home.setObjectName("lbl_del_home")
        self.lbl_del_home.setText("Удаление заказов")
        self.lbl_add_home.setObjectName("lbl_add_home")
        self.lbl_add_home.setText("Добавление новых заказов")
        self.lbl_edit_home.setObjectName("lbl_edit_home")
        self.lbl_edit_home.setText("Редактирование заказов")
        self.lbl_ingr_home.setObjectName("lbl_ingr_home")
        self.lbl_ingr_home.setText("Просмотр ингредиентов")
        self.lbl_search_home.setObjectName("lbl_search_home")
        self.lbl_search_home.setText("Поиск ингредиентов по фильтрам")

        self.orders_page.setStyleSheet("background-color: transparent;")
        self.orders_page.setObjectName("orders_page")

        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.tbl.sizePolicy().hasHeightForWidth())
        self.tbl.setSizePolicy(size_policy)

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)

        self.tbl.setFont(font)
        self.tbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbl.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tbl.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl.setAutoScroll(True)
        self.tbl.setDragDropOverwriteMode(True)
        self.tbl.setAlternatingRowColors(False)
        self.tbl.setShowGrid(False)
        self.tbl.setCornerButtonEnabled(True)
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(8)
        self.tbl.setRowCount(0)

        item = QtWidgets.QTableWidgetItem("ID")
        self.tbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem("Фамилия")
        self.tbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem("Имя")
        self.tbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem("Телефон")
        self.tbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem("Торт")
        self.tbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem("Дата принятия")
        self.tbl.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem("Дата выдачи")
        self.tbl.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem("Цена торта")
        self.tbl.setHorizontalHeaderItem(7, item)

        self.tbl.horizontalHeader().setVisible(True)
        self.tbl.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tbl.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        self.tbl.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.tbl.horizontalHeader().setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        self.tbl.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl.horizontalHeader().setStretchLastSection(True)
        self.tbl.verticalHeader().setVisible(False)
        self.tbl.verticalHeader().setCascadingSectionResizes(False)
        self.tbl.verticalHeader().setHighlightSections(False)
        self.tbl.verticalHeader().setSortIndicatorShown(False)

        self.orders_cost.setMaximumSize(QtCore.QSize(16777215, 45))
        self.orders_cost.setStyleSheet("""background-color: qlineargradient(spread:reflect, 
                                        x1:0.5, y1:0.5, x2:1, y2:0.5,
                                        stop:0.271186 rgba(255, 198, 208, 255), stop:1 rgba(255, 255, 255, 0));""")
        self.orders_cost.setObjectName("orders_cost")
        self.lbl_cost.setObjectName("lbl_cost")
        self.btns_table.setSizePolicy(size_policy)
        self.btns_table.setStyleSheet("""QPushButton {
                                          background-color: rgb(246, 148, 164);
                                      }
                                      QPushButton:hover {
                                          background-color: rgb(249, 193, 202);
                                      }""")
        self.btns_table.setObjectName("btns_table")

        self.btn_add.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_add.setObjectName("btn_add")
        self.btn_add.setText("Добавить")
        self.btn_del.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_del.setObjectName("btn_del")
        self.btn_del.setText("Удалить")
        self.btn_save.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_save.setObjectName("btn_save")
        self.btn_save.setText("Сохранить")
        self.btn_load.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_load.setObjectName("btn_load")
        self.btn_load.setText("Загрузить")

        self.products_page.setStyleSheet("background-color: transparent;")
        self.products_page.setObjectName("products_page")
        self.body_products.setObjectName("body_products")

        self.left_body.setObjectName("left_body")
        self.right_body.setObjectName("right_body")
        self.lbl_ingredients.setStyleSheet("""background-color: qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, 
                                              y2:0.5, stop:0.271186 rgba(255, 198, 208, 255), 
                                              stop:1 rgba(255, 255, 255, 0));""")
        self.lbl_ingredients.setAlignment(Qt.AlignCenter)
        self.lbl_ingredients.setObjectName("lbl_ingredients")
        self.lbl_ingredients.setText("Ингредиенты")
        self.list_ingredients.setObjectName("list_ingredients")

        self.btn_products.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_products.setText("Обновить")
        self.btn_products.setStyleSheet("""QPushButton{
                                            background-color: rgb(246, 148, 164);
                                        }
                                        QPushButton:hover{
                                            background-color: rgb(249, 193, 202);
                                        }""")
        self.btn_products.setObjectName("btn_products")

        self.sort_ingredients.setStyleSheet("""QFrame#sort_ingredients QLabel{ background-color: 
                                            qlineargradient(spread:reflect, x1:0.5, y1:0.5, x2:1, y2:0.5, 
                                            stop:0.568182 rgba(255, 154, 170, 255), 
                                            stop:1 rgba(246, 148, 164, 95));}""")
        self.sort_ingredients.setObjectName("sort_ingredients")

        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lbl_date_begin.sizePolicy().hasHeightForWidth())

        self.lbl_date_begin.setSizePolicy(size_policy)
        self.lbl_date_begin.setAlignment(Qt.AlignCenter)
        self.lbl_date_begin.setObjectName("lbl_date_begin")
        self.lbl_date_begin.setText("Начало поиска:")

        self.date_begin_ingr.setSizePolicy(size_policy)
        self.date_begin_ingr.setStyleSheet("background-color: rgb(255, 198, 208);")
        self.date_begin_ingr.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_begin_ingr.setCalendarPopup(True)
        self.date_begin_ingr.setObjectName("date_begin_ingr")

        self.lbl_date_end.setSizePolicy(size_policy)
        self.lbl_date_end.setAlignment(Qt.AlignCenter)
        self.lbl_date_end.setObjectName("lbl_date_end")
        self.lbl_date_end.setText("Конец поиска:")

        self.date_end_ingr.setSizePolicy(size_policy)
        self.date_end_ingr.setStyleSheet("background-color: rgb(255, 198, 208);")
        self.date_end_ingr.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date_end_ingr.setCalendarPopup(True)
        self.date_end_ingr.setObjectName("date_end_ingr")

        self.lbl_combo_ingr.setSizePolicy(size_policy)
        self.lbl_combo_ingr.setAlignment(Qt.AlignCenter)
        self.lbl_combo_ingr.setObjectName("lbl_combo_ingr")
        self.lbl_combo_ingr.setText("Поиск по игредиенту:")

        self.combo_ingr.setSizePolicy(size_policy)
        self.combo_ingr.setStyleSheet("background-color: rgb(255, 244, 246);")
        self.combo_ingr.setFrame(False)
        self.combo_ingr.setObjectName("combo_ingredients")
        self.combo_ingr.addItem("Все ингредиенты")

        self.empty_frame.setMinimumSize(QtCore.QSize(0, 200))
        self.empty_frame.setObjectName("empty_frame")

        self.main_footer.setMinimumSize(QtCore.QSize(0, 25))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 25))
        self.main_footer.setObjectName("main_footer")

        self.lbl_info_tbl.setSizePolicy(size_policy)
        self.lbl_info_tbl.setAlignment(Qt.AlignCenter)
        self.lbl_info_tbl.setObjectName("lbl_info_tbl")
        self.lbl_info_tbl.setStyleSheet("""font: 12pt "Microsoft YaHei UI Light";
                                        font-weight: bold;
                                        color: rgb(236, 108, 125);""")
        self.size_grip.setMinimumSize(QtCore.QSize(20, 20))
        self.size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.size_grip.setObjectName("size_grip")
