--
-- Файл сгенерирован с помощью SQLiteStudio v3.3.3 в Вс май 22 19:18:45 2022
--
-- Использованная кодировка текста: windows-1251
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Таблица: recipes
CREATE TABLE recipes (
    id_cake  INTEGER REFERENCES cake (id_cake) ON DELETE CASCADE ON UPDATE CASCADE,
    id_ingr  INTEGER REFERENCES ingredients (id_ingr) ON DELETE CASCADE ON UPDATE CASCADE,
    count    DOUBLE,
    id_unit  INTEGER REFERENCES units (id_unit) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO recipes (
                        id_cake,
                        id_ingr,
                        count,
                        id_unit
                    )
                    VALUES (
                        1,
                        1,
                        125.0,
                        1
                    ),
                    (
                        1,
                        2,
                        500.0,
                        1
                    ),
                    (
                        1,
                        3,
                        3.0,
                        7
                    ),
                    (
                        1,
                        4,
                        1.0,
                        6
                    ),
                    (
                        1,
                        5,
                        2.0,
                        5
                    ),
                    (
                        1,
                        6,
                        1000.0,
                        1
                    ),
                    (
                        1,
                        7,
                        500.0,
                        1
                    ),
                    (
                        2,
                        5,
                        4.0,
                        5
                    ),
                    (
                        2,
                        1,
                        75.0,
                        1
                    ),
                    (
                        2,
                        6,
                        225.0,
                        1
                    ),
                    (
                        2,
                        2,
                        310.0,
                        1
                    ),
                    (
                        2,
                        16,
                        500.0,
                        1
                    ),
                    (
                        2,
                        8,
                        250.0,
                        3
                    ),
                    (
                        2,
                        18,
                        2.0,
                        7
                    ),
                    (
                        2,
                        17,
                        500.0,
                        3
                    ),
                    (
                        3,
                        6,
                        850.0,
                        1
                    ),
                    (
                        3,
                        1,
                        750.0,
                        1
                    ),
                    (
                        3,
                        5,
                        6.0,
                        5
                    ),
                    (
                        3,
                        8,
                        150.0,
                        3
                    ),
                    (
                        3,
                        9,
                        3.0,
                        7
                    ),
                    (
                        3,
                        10,
                        1.0,
                        7
                    ),
                    (
                        3,
                        11,
                        5.0,
                        1
                    ),
                    (
                        3,
                        12,
                        1.0,
                        4
                    ),
                    (
                        3,
                        2,
                        300.0,
                        1
                    ),
                    (
                        3,
                        13,
                        20.0,
                        1
                    ),
                    (
                        4,
                        5,
                        4.0,
                        5
                    ),
                    (
                        4,
                        14,
                        2.0,
                        5
                    ),
                    (
                        4,
                        6,
                        400.0,
                        1
                    ),
                    (
                        4,
                        4,
                        1.0,
                        6
                    ),
                    (
                        4,
                        15,
                        500.0,
                        3
                    ),
                    (
                        4,
                        11,
                        5.0,
                        1
                    );

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
